name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Manuscript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: |
        curl -fsSL https://get.pulumi.com | sh
        export PATH="$PATH:$HOME/.pulumi/bin"
        make
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        TZ: America/Los_Angeles
